Translation/from en to it
swirle13/The-Witcher-Old-World-Tool pull request #108
Opened 2023-12-09 16:57 UTC by RaydenMK

Last version of the file with added rows translated.

2023-12-28 20:18 UTC, swirle13 requested changes
So very good, thank you so much. Just a few really small things and it should all be good to merge!

2023-12-28 20:18 UTC, swirle13 commented on src/locales/it/translation.json
> +         "card": {
```suggestion
        "card": {
```

This accidentally had an additional space included, which will prevent the json from being valid and working properly.

2023-12-28 20:18 UTC, swirle13 commented on src/locales/it/translation.json
> +            "header": "Se su due colonne: leggi da sinistra a destra, dall'alto in basso. Ciò garantirà che i totali parziali delle carte distribuite su più mazzi (ad esempio \"Carte Mostro: 11 (29/1
Does italian count items out of a total number of items in a flipped order, e.g. "29 total, 11 so far"?

The value here, "11/29", is equal to "11 out of the total 29 items so far". I'm assuming this was an accidental recognition of this being a date, November 29, and flipping it to be accurate for Italian, do I have that correct?

2023-12-28 20:18 UTC, swirle13 commented on src/locales/it/translation.json
>          "Difficulty Jumbo Reference cards": "Difficulty Jumbo Reference cards",
Do you need to translate this line as well?

2023-12-28 20:18 UTC, swirle13 commented on src/locales/it/translation.json
> +                "link": "https://github.com/swirle13/The-Witcher-Old-World-Tool-Issues/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=%5BBUG%5D+"
can you update this to the previous version? I have updated this url to consolidate to the primary repo now that it is public.

```suggestion
                "link": "https://github.com/swirle13/The-Witcher-Old-World-Tool/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=%5BBUG%5D+"
```

2023-12-28 20:18 UTC, swirle13 commented on src/locales/it/translation.json
> +                "link": "https://github.com/swirle13/The-Witcher-Old-World-Tool-Issues/issues/new?assignees=&labels=enhancement&projects=&template=feature_request.md&title=%5BENHANCEMENT%5D+"
```suggestion
                "link": "https://github.com/swirle13/The-Witcher-Old-World-Tool/issues/new?assignees=&labels=enhancement&projects=&template=feature_request.md&title=%5BENHANCEMENT%5D+"
```

2023-12-28 20:18 UTC, swirle13 commented on src/locales/it/translation.json
> +                "link": "https://github.com/swirle13/The-Witcher-Old-World-Tool-Issues/discussions"
```suggestion
                "link": "https://github.com/swirle13/The-Witcher-Old-World-Tool/discussions"
```

2023-12-28 20:18 UTC, swirle13 commented on src/locales/it/translation.json
> +                "link": "https://github.com/swirle13/The-Witcher-Old-World-Tool-Issues/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc"
```suggestion
                "link": "https://github.com/swirle13/The-Witcher-Old-World-Tool/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc"
```

2024-01-10 14:54 UTC, RaydenMK commented
> So very good, thank you so much. Just a few really small things and it should all be good to merge!

@swirle13 
I did the corrections requested. Do you think it can be merged?

2024-01-10 20:10 UTC, swirle13 approved these changes
Looks good, tested with no issues on my local machine!

2024-01-10 20:10 UTC, merged