FR Translation - new format on Swirle's translation branch
swirle13/The-Witcher-Old-World-Tool pull request #15
Opened 2023-09-26 11:38 UTC by HughMcZus

2023-09-26 18:00 UTC, swirle13 commented
There are a few changes that are in my new commits that aren't in here.

- `common` was updated to remove some unused values https://github.com/swirle13/The-Witcher-Old-World-Tool/commit/eae76fe490647e28c051f4c019654e2d739f43bf#diff-f42562c98e440b987ac05f6dd6a75797b81b5d6a090db09faaee014f0478aff6L2-L26
- `setupHelper.base.playerSetup.markers` and `markersMages` were updated to reduce confusion on where to place the markers on the player cards: https://github.com/swirle13/The-Witcher-Old-World-Tool/commit/eae76fe490647e28c051f4c019654e2d739f43bf#diff-f42562c98e440b987ac05f6dd6a75797b81b5d6a090db09faaee014f0478aff6R235-R236
- `setupHelper.dagon` and `dagonMT` were updated to improve language and include Dagon Trail tokens https://github.com/swirle13/The-Witcher-Old-World-Tool/commit/eae76fe490647e28c051f4c019654e2d739f43bf#diff-f42562c98e440b987ac05f6dd6a75797b81b5d6a090db09faaee014f0478aff6R354-R355

I'm unsure if your changes include these differences in french, as I don't speak it, but from what it looks like, they don't appear to contain these changes.

2023-09-26 18:56 UTC, swirle13 commented
And this is my fault. I didn't double check that keys get updated when I run the script to add additional keys. I'll do this in my following commit(s)

2023-09-26 18:59 UTC, HughMcZus commented
Done :) Thanks

2023-09-27 00:02 UTC, swirle13 requested changes
Looks great so far, just a few of the recent changes need to be integrated and it should be good to go after that 👍🏼

2023-09-27 00:02 UTC, swirle13 commented on src/locales/fr/translation.json
> +                "text": "Discord officiel",
can you update to `"text": "$t(communityLinks.officialDiscord)",`?

2023-09-27 20:37 UTC, swirle13 approved these changes
Looks great, thank you so much!

2023-09-27 20:37 UTC, merged